[build]
  # Directory where the build command is executed and package.json resides
  base = "Algoflow"

  # Directory (relative to the base directory) containing the built assets
  publish = "dist"

  # Command to compile the project
  command = "npm run build"

# Redirect rule to handle SPA routing if the app starts using client-side routes,
# and to prevent 404s on page reloads.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
